message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        # Just show something if there are violations
        header: ""
        footer: ""
    updated:  # Messages when new commits are added to the PR
        header: ""
        footer: ""
    no_errors: "No PEP8 issues."

scanner:
    diff_only: False  # If True, errors caused by only the patch are shown

pycodestyle:
    max-line-length: 79  # Default is 79 in PEP8
    ignore:  # Errors and warnings to ignore
        - E402

only_mention_files_with_errors: True  # If False, a separate status comment for each file is made.
descending_issues_order: False # If True, PEP8 issues in message will be displayed in descending order of line numbers in the file
